name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build
  DeployDevelopment:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      pages: write
      id-token: write
    environment:
      name: 'New Roofstock onChain'
      url: 'https://new.roofstockonchain.com'
    steps:
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v2
