name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Prettier
        run: npm run prettier
